install-new-version:
	dotnet publish -c Release -r osx-arm64 -p:PublishSingleFile=true -p:PublishTrimmed=true -p:IncludeAllContentForSelfExtract=true -p:SelfContained=true
	sudo mv /Users/duke/Dev/Personal/TypescriptGenerator/src/TypescriptGenerator.Console/bin/Release/net10.0/osx-arm64/publish/TypescriptGenerator.Console /usr/local/bin/tsgen
